title: Nanlou
description: nanlou's blog

url: https://nanlou.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: nanlou
  #twitter: brianmaierjr
  #facebook: brianmaierjr
  email: zengw317@gmail.com
  #linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: nanlou
